### ISSUE TITLE
Этот else логически не правильный (т.к. если условие меньше 150000, он всегда будет срабатывать)

### ISSUE THREAD

**Issue by coursar** [RuselSam/sportmasterBonuses#4]
https://github.com/RuselSam/sportmasterBonuses/blob/7dadb2d5664e51d7aff790b49c4ee2be652e3451/src/main/java/sportmasterBonuses.java#L23-L25

**Comment by RuselSam** [comment]
Это условие срабатывает после всех if, вроде работает:

![sportmaster](https://user-images.githubusercontent.com/20902091/65570554-231ad800-df6a-11e9-8d77-0c2848a9d18b.png)


или я не правильно понял?

**Comment by coursar** [comment]
Этот `else` работает только когда `if`, который к нему привязан - не срабатывает:
https://github.com/RuselSam/sportmasterBonuses/blob/e27596864e41b14d985c68961cdf9e31f26b4c0e/src/main/java/SportmasterBonuses.java#L27-L33

Логическая ошибка в том, что вы сравниваете почему-то сумму с размером бонуса третьего уровня, когда должны сравнивать со 150_000

**Comment by coursar** [comment]
И пишется award, а не avard
